# Bài này cực kì khó
# Nếu không có replace thì tam giác sẽ bị dời ra 1 đoạn chẳng hạn:
# - Không có replace: (với giá trị n = 9)
#|      .
#|     ...
#|    .....
#|   .......
#|  .........
# - Có replace: (với giá trị n = 9)
#|    .
#|   ...
#|  .....
#| .......
#|.........

while True:
    n = int(input('Nhập độ dài cạnh đáy của tam giác cân: '))
    if n % 2 == 1 and n >= 3:
        break
    print('Không thể vẽ được tam giác cân với số chẵn hoặc số bé hơn 3')

t = 0
for i in range(1, n+1, 2):
    t += 1
    print((' '*(n - t - 2) + '.'*i).replace(' ', '', int((n-5)/2)))
